### ISSUE TITLE
get_tickers não está funcionando

### ISSUE THREAD

**Issue by cobap** [NathanMoura/fundamentos#2]
Nathan, primeiramente parabéns pelo projeto! Era exatamente algo assim que estava buscando. Estou criando um projeto de datascience que otimiza escolha fundamentalista, e precisava "digitalizar" os dados do fundamentus. Ficou show de bola!!

Cara, por algum motivo que não consegui identificar o get_tickers() não está rodando. Segue abaixo print do erro
 
![image](https://user-images.githubusercontent.com/6344807/96189319-a4972c80-0f16-11eb-85f3-03718a9888a4.png)

**Comment by nathanmoura** [comment]
Opa, valeu mesmo! Eu percebi que os métodos relacionados ao fundamentus não estão funcionando (get_balanco, get_tickers, get_dre). Só estão funcionando os métodos do ADVFN (get_fundamentos). Vou checar até o final da semana que vem pra tentar arrumar.

**Comment by cobap** [comment]
Nathan, só get_ticker que não ta funcionando. Acabei de testar get_dre e get_balanco e retornou OK os resultados

![image](https://user-images.githubusercontent.com/6344807/96291763-ed0a2500-0fbe-11eb-8927-7865812380d0.png)

Vi que a origem do erro está vindo qd faz o scrap da URL 'http://fundamentus.com.br/detalhes.php' e tenta converter a tabela que aparece listando todas as ações. O pessoal do site deve ter mudado alguma coisa no HTML que travou o código. To meio corrido aqui. Vou tentar ver durante o fds tb, te aviso se tiver algum update

**Comment by aracoara** [comment]
Parabéns pelo projeto, Natan!

O get_tickers ainda não está funcionando. Alguma sugestão de como obter a lista do tickers?

**Comment by cobap** [comment]
@aracoara @NathanMoura tudo bem? Havia até esquecido desse problema. Consegui resolver rapidinho com o read_html do pandas. 

![image](https://user-images.githubusercontent.com/6344807/104824887-c44f3100-5834-11eb-9046-96922de5fb54.png)

@aracoara enquanto o Nathan não sobe um update, segue esse código que é sucesso

Abçs

**Comment by nathanmoura** [comment]
Opa galera, desculpem a demora. Estava envolvido em outros projetos e não me sobrou tempo pra lib fundamentos.

De qualquer forma, está resolvido! 

O problema era que eu havia esquecido de gerar `User-Agents` aleatórios no método `get_tickers`, como fiz nos outros da biblioteca e o site fundamentus já tinha bloqueado o `User-Agent` padrão da lib `requests` hahaha.
