### ISSUE TITLE
Erro quarterly=True

### ISSUE THREAD

**Issue by faissalhajar** [NathanMoura/fundamentos#4]
Nathan, parabéns pelo projeto! Tenho procurado várias fontes recentemente e a sua foi a mais robusta de todas! Encontrei um erro ao usar o método get_balanco() e passar quarterly=True, com um output de "ValueError: Cannot convert non-finite values (NA or inf) to integer"

`import fundamentos as ftos
df = ftos.get_balanco('ITUB4', quarterly=True)
df`

output:

`/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/dtypes/cast.py in astype_nansafe(arr, dtype, copy, skipna)
    866 
    867         if not np.isfinite(arr).all():
--> 868             raise ValueError("Cannot convert non-finite values (NA or inf) to integer")
    869 
    870     elif is_object_dtype(arr):

ValueError: Cannot convert non-finite values (NA or inf) to integer`

Não consegui corrigir o erro, mas os dados anuais funcionam perfeitamente. Desde já, obrigado!

**Comment by seurafinha** [comment]
Aqui dá o mesmo erro

**Comment by lucaspenna00** [comment]
Aparentemente o Fundamentus criou um "captcha" para acessar a página de download dos dados trimestrais. Provavelmente o Scrapper não foi atualizado para resolver o captcha... Recomendo a paciência para fazer o download das DREs e Balanços de forma manual no site.

**Comment by nathanmoura** [comment]
Olá amigos, desculpem a demora pra resolver o problema. Estava com alguns projetos pessoais e não consegui checar. Hoje estudarei como resolver. 

Mas já de antemão: o problema não é o captcha! O meu código o contorna. Aparentemente o problema está no fato de eu converter as planilhas para `int`. Isso não dava problema antes, mas agora algumas planilhas estão vindo com dados vazios (NaN).

**Comment by lucaspenna00** [comment]
Fica de sugestão: 
A CVM também divulga os balanços e DREs das empresas de capital aberto. A divulgação é até mais detalhada que a do Fundamentus e o download dos dados também é bem simples de implementar, já que o site não tem captcha e ela já fornece um ZIP com todos as empresas em um ano. Pode ser um incremento bacana para o repositório e acho que tb pode ser uma solução mais estável que o Fundamentus. 

http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DADOS/ 

Abraços Nathan! Obg pelo seu trabalho

**Comment by nathanmoura** [comment]
Pronto, amigos. Resolvido! Podem usar o `quarterly=True` agora.

**Comment by nathanmoura** [comment]
> Fica de sugestão:
> A CVM também divulga os balanços e DREs das empresas de capital aberto. A divulgação é até mais detalhada que a do Fundamentus e o download dos dados também é bem simples de implementar, já que o site não tem captcha e ela já fornece um ZIP com todos as empresas em um ano. Pode ser um incremento bacana para o repositório e acho que tb pode ser uma solução mais estável que o Fundamentus.
> 
> http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DADOS/
> 
> Abraços Nathan! Obg pelo seu trabalho

Sim!! Excelente ideia.

Eu já conhecia essa alternativa, inclusive tenho um código pronto de webscrapping diretamente pela CVM. Mas fiquei receoso de atualizar a biblioteca fundamentos, pois isso poderia gerar incompatibilidades com aqueles que já a utilizam há algum tempo...
